layout_spectrum: 0.3135961585212499
typography_spectrum: 0.14431015914306045
color:
  saturation: 0.8890855526551604
  brandStrength: 0.8579782033339143
  rhythmicContrast: 0.25364420912228525
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.26028120517730713
title: martín garrocho
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'Creative Director from the Atlantic, living in the pacific.'
name: grr8
