title: martín garrocho
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6899642
  brandStrength: 0.1057348
  lightness: 0.7939068
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#BBBBBB'
    - '#434343'
    - '#868686'
  rhythmicContrast: 0.8997844
typography_spectrum: 1
description: 'Creative Director from the Atlantic, living in the pacific.'
layout_spectrum: 0.5430108
name: grr8
